name: saltstack-tomcat-formula
source: https://github.com/bechtoldt/saltstack-tomcat-formula
summary: SaltStack Formula to set up and configure Tomcat, an application server that executes Java servlets and renders Web pages
todo:
  - add instructions how to use formhelper, add information about it in the formula-docs (dependency), show up alternative?
  - 'table/ matrix: os/salt compatibility (dedicated file)'
  - add list of available states
  - add tests
